Allow users manage own access keys
cloudposse/terraform-aws-iam-assumed-roles pull request #10
Opened 2018-12-19 16:10 UTC by goruha

## What
* Allow users to manage own access keys

## Why
* If they can manage passwords, they should be able to manage access keys

2018-12-19 20:53 UTC, osterman commented
Fix CI

2018-12-19 20:54 UTC, osterman commented on main.tf
> +  description = "Allow admin users to manage own access keys"
```suggestion
  description = "Allow admin users to manage their own access keys"
```

2018-12-19 20:55 UTC, osterman commented on main.tf
> +data "aws_iam_policy_document" "allow_manage_access_keys" {
```suggestion
data "aws_iam_policy_document" "allow_key_management" {
```

2018-12-19 20:55 UTC, osterman commented on main.tf
> +resource "aws_iam_policy" "allow_manage_access_keys_admin" {
```suggestion
resource "aws_iam_policy" "allow_key_management" {
```

2018-12-19 20:56 UTC, osterman commented on main.tf
> +  name        = "${module.admin_label.id}-permit-manage-keys"
```suggestion
  name        = "${module.admin_label.id}-allow-key-management"
```

Suggest using new `label` to follow convention and enforce use of `var.delimiter`

2018-12-19 20:57 UTC, osterman commented on main.tf
> +  description = "Allow readonly users to manage own access keys"
```suggestion
  description = "Allow readonly users to manage their own access keys"
```

2018-12-19 20:58 UTC, osterman commented on main.tf
> +resource "aws_iam_group_policy_attachment" "manage_access_key_admin" {
```suggestion
resource "aws_iam_group_policy_attachment" "key_management" {
```

2018-12-20 10:25 UTC, osterman commented
Fix CI

2018-12-21 01:39 UTC, osterman requested changes
They can already do this, pretty sure. They just need to assume role first. They *should not* be able to create any access keys without MFA. The changes in this PR don't seem to require MFA.  The password stuff was done (without MFA) so they can self-register after receiving an invitation link. The same is not true for keys.

2018-12-22 01:06 UTC, goruha commented
> They can already do this, pretty sure.
Nope. Only admin roles can manage the keys.
> They just need to assume role first.
Assume role - readonly allow only to read, not to renew or create another one.

>  They should not be able to create any access keys without MFA.
Done.
> The changes in this PR don't seem to require MFA. 
Done

> The password stuff was done (without MFA) so they can self-register after receiving an invitation link. > > The same is not true for keys.
Done

2018-12-22 01:30 UTC, osterman approved these changes

2018-12-22 03:09 UTC, aknysh approved these changes

2018-12-26 10:16 UTC, merged