Use `label` pattern
cloudposse/terraform-aws-iam-assumed-roles pull request #3
Opened 2018-03-28 18:21 UTC by aknysh

## what
* Use `label` pattern
* Add TravisCI

## why
* `label` pattern is a common pattern for safely naming resources and avoid naming conflicts
* To monitor build status

2018-03-28 21:00 UTC, osterman submitted a review, later dismissed

2018-03-28 21:02 UTC, osterman commented on main.tf
> +  name   = "AllowChangePassword"
this is unsafe

2018-03-28 21:02 UTC, osterman commented on main.tf
> +  name   = "AllowUsersToDeactivateTheirOwnVirtualMFADevice"
This is unsafe

2018-03-28 21:28 UTC, aknysh commented on main.tf
> +  name   = "AllowUsersToDeactivateTheirOwnVirtualMFADevice"
updated

2018-03-29 00:35 UTC, osterman commented on main.tf
> +  name        = "${module.admin_label.id}${var.delimiter}AllowUsersToDeactivateTheirOwnVirtualMFADevice"
not keen on mixing camel case with hyphens. Also, we don't need the precision of `AllowUsersToDeactivateTheirOwnVirtualMFADevice`. 

e.g. 

cp-prod-mfa-management is good enough.

2018-03-29 00:36 UTC, osterman commented on main.tf
> +  name        = "${module.admin_label.id}${var.delimiter}AllowChangePassword"
perhaps something like `cp-prod-permit-change-password`

2018-03-29 00:37 UTC, osterman requested changes
Don't mix camel case with hyphens

2018-03-29 19:34 UTC, osterman approved these changes

2018-03-29 19:41 UTC, merged