Add support for a sub-provider to roles
cloudposse/terraform-aws-iam-assumed-roles pull request #7
Opened 2018-08-06 14:29 UTC by ArdaXi

What
------

Add an option to use a sub-provider for roles, so they can be created in a different account than the users who can assume it.

Why
------

We have a use-case where we need admin and readonly roles in subaccounts, which people access via the main account. With this change, we can use this module to do this easily by using multiple providers.

2018-08-07 05:09 UTC, osterman commented on README.yaml
> +    github: "aknysh"
Feel free to add yourself as a contributor

2018-08-07 05:09 UTC, osterman approved these changes
LGTM. I like the pattern you're introducing. Have you seen this in other modules?

2018-08-07 05:15 UTC, osterman commented
Shoot...looks like it breaks CI.

```
Error getting plugins: module root: 1 error(s) occurred:
* module : provider alias must be defined by the module or a parent: ${var.use_sub_provider ? aws.sub : aws}
make: *** [terraform/get-plugins] Error 1
The command "make terraform/get-plugins" exited with 2.
0.29s$ make terraform/get-modules
Error getting plugins: module root: 1 error(s) occurred:
* module : provider alias must be defined by the module or a parent: ${var.use_sub_provider ? aws.sub : aws}
make: *** [terraform/get-modules] Error 1
The command "make terraform/get-modules" exited with 2.
```

Have you tested this where no secondary provider exists?

2018-08-07 05:16 UTC, osterman requested changes
Looks like we've introduced a dependency on a secondary provider. We need to make sure this module remains compatible. Any suggestions for how to mitigate?

2018-08-07 05:56 UTC, ArdaXi commented
It would have been a nice pattern, a last-minute change that I didn't test beforehand, my apologies. Turns out Terraform does not support interpolation in providers because they're interpreted before any interpolation happens.

I don't think there's a way to do this in a way that is directly backwards-compatible. It would work fine if it's called with

```
providers = {
   aws     = "aws"
   aws.sub = "aws"
}
```

but obviously that will break things if users don't change it manually.

2018-08-07 06:33 UTC, ArdaXi commented
I've tried a few things and I don't think there's a way to make this work without a dependency on another module. If we want to keep backwards compatibility I think this needs to happen in a new module altogether.

I wonder if this usecase actually makes sense? It seems to me like if you're doing role assumptions you'll want to be able to do so across accounts.

2018-08-07 16:25 UTC, aknysh commented
@ArdaXi  thank you for testing the module and submitting the PR.
To me it looks like it's not necessary for a few reasons:

1. Take a look at how we create cross-account roles and groups to allow assuming the roles:
https://github.com/cloudposse/terraform-aws-organization-access-role
https://github.com/cloudposse/terraform-aws-organization-access-group
Note that `OrganizationAccountAccessRole` is just a convenient example (AWS recommends using the name and creates it automatically in member accounts), but you can create any role with any name and a group to assume that role.

2. Placing `providers` in a low-level modules is not a good idea because:

a) It introduces many dependencies and in some cases don't work at all

b) Low-level module usually don't need to make any decisions on how and where they are used - the decision belongs to top-level modules. `provider` works from top-level modules and will propagate to the low-level modules, for example
https://github.com/cloudposse/terraform-root-modules/blob/master/aws/acm-cloudfront/main.tf#L11
No need to place it at the low-level.

c) In some cases, we want to use a provider with different properties, for example, if we want to use `assume_role` 
https://github.com/cloudposse/terraform-root-modules/blob/master/aws/root-iam/main.tf#L16
In this case, we'll have two `providers` (hardcoded one in the `terraform-aws-iam-assumed-roles` module`, another in the top-level module. It does not look good/dry, but more importantly you can't tell how the system works and what properties Terraform will take from the two providers (unless you test it to know for sure).

2018-08-07 16:26 UTC, aknysh requested changes
see comments

2018-08-07 16:30 UTC, osterman reviewed
@aknysh the problem he is trying to solve is when you need to create new roles and permissions in subaccounts. The OrganziationalAccessRole we have been using is a one off exception. He wants to be able to create, for example, a read only role in a sub account.

2018-08-07 16:55 UTC, aknysh commented
in this case, we can use the module as it is and use an external `provider` in the top-level module.
As we do here https://github.com/cloudposse/terraform-root-modules/tree/master/aws/root-iam
I think it's much cleaner, and the provider could have any attributes (not hardcoded in `terraform-aws-iam-assumed-roles` module)

2018-08-13 23:24 UTC, osterman commented
@ArdaXi I think we might need to wait until terraform 0.12. perhaps then, we can make this more dynamic.

2024-03-08 13:01 UTC, closed without merging